USE QuanLySieuThi;
GO

-- Xóa theo thứ tự từ bảng phụ thuộc đến bảng cha để script chạy lại an toàn.
DROP TABLE IF EXISTS THANH_TOAN;
DROP TABLE IF EXISTS CT_HOA_DON;
DROP TABLE IF EXISTS HOA_DON;
DROP TABLE IF EXISTS CT_PHIEU_NHAP;
DROP TABLE IF EXISTS PHIEU_NHAP;
DROP TABLE IF EXISTS KHACH_HANG;
DROP TABLE IF EXISTS NHAN_VIEN;
DROP TABLE IF EXISTS SAN_PHAM;
DROP TABLE IF EXISTS NHA_CUNG_CAP;
DROP TABLE IF EXISTS DANH_MUC;
GO

CREATE TABLE DANH_MUC (
    MaDM VARCHAR(10) NOT NULL,
    TenDM NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_DANH_MUC PRIMARY KEY (MaDM),
    CONSTRAINT UQ_DANH_MUC_TenDM UNIQUE (TenDM)
);

CREATE TABLE NHA_CUNG_CAP (
    MaNCC VARCHAR(10) NOT NULL,
    TenNCC NVARCHAR(150) NOT NULL,
    DiaChi NVARCHAR(255) NULL,
    DienThoai VARCHAR(15) NOT NULL,
    Email VARCHAR(100) NULL,
    CONSTRAINT PK_NHA_CUNG_CAP PRIMARY KEY (MaNCC),
    CONSTRAINT UQ_NCC_DienThoai UNIQUE (DienThoai),
    CONSTRAINT CK_NCC_Email CHECK (Email IS NULL OR Email LIKE '%_@_%._%')
);

CREATE TABLE NHAN_VIEN (
    MaNV VARCHAR(10) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    ChucVu NVARCHAR(50) NOT NULL DEFAULT N'Nhân viên bán hàng',
    DienThoai VARCHAR(15) NOT NULL,
    NgayVaoLam DATE NOT NULL DEFAULT CONVERT(date, GETDATE()),
    Luong DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_NHAN_VIEN PRIMARY KEY (MaNV),
    CONSTRAINT UQ_NV_DienThoai UNIQUE (DienThoai),
    CONSTRAINT CK_NV_Luong CHECK (Luong > 0)
);

CREATE TABLE KHACH_HANG (
    MaKH VARCHAR(10) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    DienThoai VARCHAR(15) NOT NULL,
    DiemTichLuy INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_KHACH_HANG PRIMARY KEY (MaKH),
    CONSTRAINT UQ_KH_DienThoai UNIQUE (DienThoai),
    CONSTRAINT CK_KH_Diem CHECK (DiemTichLuy >= 0)
);

CREATE TABLE SAN_PHAM (
    MaSP VARCHAR(10) NOT NULL,
    TenSP NVARCHAR(150) NOT NULL,
    DonViTinh NVARCHAR(30) NOT NULL DEFAULT N'Cái',
    GiaBan DECIMAL(18,2) NOT NULL,
    SoLuongTon INT NOT NULL DEFAULT 0,
    MaDM VARCHAR(10) NOT NULL,
    CONSTRAINT PK_SAN_PHAM PRIMARY KEY (MaSP),
    CONSTRAINT CK_SP_GiaBan CHECK (GiaBan > 0),
    CONSTRAINT CK_SP_SoLuong CHECK (SoLuongTon >= 0),
    CONSTRAINT FK_SP_DANH_MUC FOREIGN KEY (MaDM) REFERENCES DANH_MUC(MaDM)
);

CREATE TABLE PHIEU_NHAP (
    MaPN VARCHAR(10) NOT NULL,
    NgayNhap DATE NOT NULL DEFAULT CONVERT(date, GETDATE()),
    MaNCC VARCHAR(10) NOT NULL,
    MaNV VARCHAR(10) NOT NULL,
    TongTien DECIMAL(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT PK_PHIEU_NHAP PRIMARY KEY (MaPN),
    CONSTRAINT CK_PN_TongTien CHECK (TongTien >= 0),
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC),
    CONSTRAINT FK_PN_NV FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE CT_PHIEU_NHAP (
    MaPN VARCHAR(10) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    SoLuongNhap INT NOT NULL,
    DonGiaNhap DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_CT_PHIEU_NHAP PRIMARY KEY (MaPN, MaSP),
    CONSTRAINT CK_CTPN_SoLuong CHECK (SoLuongNhap > 0),
    CONSTRAINT CK_CTPN_DonGia CHECK (DonGiaNhap > 0),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MaPN) REFERENCES PHIEU_NHAP(MaPN),
    CONSTRAINT FK_CTPN_SP FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE HOA_DON (
    MaHD VARCHAR(10) NOT NULL,
    NgayLap DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
    MaKH VARCHAR(10) NULL,
    MaNV VARCHAR(10) NOT NULL,
    TongTien DECIMAL(18,2) NOT NULL DEFAULT 0,
    TrangThai NVARCHAR(30) NOT NULL DEFAULT N'Chưa thanh toán',
    CONSTRAINT PK_HOA_DON PRIMARY KEY (MaHD),
    CONSTRAINT CK_HD_TongTien CHECK (TongTien >= 0),
    CONSTRAINT CK_HD_TrangThai CHECK (TrangThai IN (N'Chưa thanh toán', N'Đã thanh toán', N'Đã hủy')),
    CONSTRAINT FK_HD_KH FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH),
    CONSTRAINT FK_HD_NV FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE CT_HOA_DON (
    MaHD VARCHAR(10) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    SoLuong INT NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_CT_HOA_DON PRIMARY KEY (MaHD, MaSP),
    CONSTRAINT CK_CTHD_SoLuong CHECK (SoLuong > 0),
    CONSTRAINT CK_CTHD_DonGia CHECK (DonGia > 0),
    CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaHD) REFERENCES HOA_DON(MaHD),
    CONSTRAINT FK_CTHD_SP FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE THANH_TOAN (
    MaTT VARCHAR(10) NOT NULL,
    MaHD VARCHAR(10) NOT NULL,
    NgayThanhToan DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
    SoTien DECIMAL(18,2) NOT NULL,
    PhuongThuc NVARCHAR(30) NOT NULL,
    TrangThai NVARCHAR(30) NOT NULL DEFAULT N'Thành công',
    CONSTRAINT PK_THANH_TOAN PRIMARY KEY (MaTT),
    CONSTRAINT UQ_THANH_TOAN_MaHD UNIQUE (MaHD),
    CONSTRAINT CK_TT_SoTien CHECK (SoTien > 0),
    CONSTRAINT CK_TT_PhuongThuc CHECK (PhuongThuc IN (N'Tiền mặt', N'Chuyển khoản', N'Thẻ', N'Ví điện tử')),
    CONSTRAINT CK_TT_TrangThai CHECK (TrangThai IN (N'Thành công', N'Thất bại')),
    CONSTRAINT FK_TT_HD FOREIGN KEY (MaHD) REFERENCES HOA_DON(MaHD)
);
GO

CREATE INDEX IX_CTPN_MaSP ON CT_PHIEU_NHAP(MaSP);
CREATE INDEX IX_CTHD_MaSP ON CT_HOA_DON(MaSP);
CREATE INDEX IX_HD_NgayLap_TrangThai ON HOA_DON(NgayLap, TrangThai);
GO
